# Generated by Django 4.2.7 on 2024-02-15 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business_employment_data',
            name='data_value',
            field=models.CharField(max_length=100),
        ),
    ]
